// Edges:
"AB"
"[R2 U' :[U2, S']]"
"AD"
"[L2 U :[U2, S]]"
"AE"
"[S' U :[U2, S]]"
"AF"
"[U' :[L' S L, U2]]"
"AG"
"[U :[L E L', U2]]"
"AH"
"[U' :[R E' R', U2]]"
"AJ"
"[R' U' :[U2, S']]"
"AK"
"[U' M U :[U2, M]]"
"AL"
"[L U :[U2, S]]"
"AM"
"[S U :[U2, S']]"
"AN"
"[U :[L' E L, U2]]"
"AO"
"[U' :[R' E' R, U2]]"
"AP"
"[U :[R S' R', U2]]"
"AQ"
"U' S R' F' R S' R' F R U' M' U2 M"
"AR"
"[L' U :[U2, S]]"
"AS"
"[U' M' U :[U2, M']]"
"AT"
"[R U' :[U2, S']]"
"AU"
"[U2, M']"
"AV"
"[U' :[U2, S']]"
"AW"
"[M, U2]"
"AX" // 21 A's
"[U :[U2, S]]"
"BD"
"[F2 U :[M', U2]]"
"BE"
"[L' U' L, S]"
"BF"
"[U', L' S L]"
"BG"
"[U :[L E L', U]]"
"BH"
"[U', L S L']"
"BJ"
"[U :[L' E2 L, U]]"
"BK"
"[x :[U' R' U, M]]"
"BL"
"[U', R E2 R']"
"BM"
"R' E2 R2 E' R' U' R E R2 E2 R U"
"BN"
"[U :[R' S' R, U]]"
"BO"
"[U', R E R']"
"BP"
"[U :[R S' R', U]]"
"BQ"
"[U :[R' F R, S]]"
"BR"
"[U', R' E2 R]"
"BS"
"[D' :[U', R' E' R]]"
"BT"
"[U :[L E2 L', U]]"
"BU" 
"R2 f2 R2 U' R2 f2 R2 U'"
"BV"
"U2 R U R' U' R' U' R' U R U'"
"BW"
"[M2, R U' R' U]"
"BX" // 20 B's
"U' L' U' L U L U L U' L'"
"DE"
"L E2 L2 E L U L' E' L2 E2 L' U'"
"DF"
"[U' :[L' S L, U']]"
"DG"
"[R U R', S]"
"DH"
"[U' :[L S L', U']]"
"DJ"
"[U, R' S2 R]"
"DK"
"[x :[U L U', M]]"
"DL"
"U2 L U L U L' U' L' U' L' U"
"DM"
"[R U R', S']"
"DN"
"[U, R' S' R]"
"DO"
"[U' :[R E R', U']]"
"DP"
"[U, R S' R']"
"DQ"
"[M, L' U L U']"
"DR"
"L' U' L' U' L' U L U L U"
"DS"
"[D :[U, L E L']]"
"DT"
"U' R U R U R U' R' U' R'"
"DU"
"R2 f2 R2 U R2 f2 R2 U"
"DV"
"U R U R' U' R' U' R' U R"
"DW"
"D' U R U R' U' R' U' R' U R D"
"DX"
"U' L U L' U' L' U' L' U L U2"
"EF"
"[r' :[U M2 U', L']]"
"EG"
"[L2, D M D']"
"EH"
"[r' :[U M2 U', L]]"
"EJ"
"[F R U :[U2, M']]"
"EK"
"[x :[M', U' L U]]"
"EL"
"[F' :[L', U M2 U']]"
"EM"
"[R F R' :[R2, S]]"
"EN"
"[r' U :[M', U2]]"
"EO"
"[x' z' :[M2, U R U']]"
"EP"
"[x' z' :[U' M2 U, R]]"
"EQ"
"[U' :[S, R' F R]]"
"ER"
"[U' F' L :[S', L2]]"
"ES"
"[x U' :[U' M' U, L]]"
"ET"
"[R' :[S, L U' L']]"
"EU"
"[x L' D :[U2, M']]"
"EV"
"[L :[F', L S L']]"
"EW"
"[x :[M2, U' L U]]"
"EX"
"[L' :[E, L' U L]]"
"FG"
"[L, U S' U']"
"FH"
"[x' :[L2, U M2 U']]"
"FJ"
"[z' :[M', U L' U']]"
"FK"
"[M' :[M', U' L' U]]"
"FL"
"z' x L E2 L2 E L U L' E' L2 E2 L' U' x' z"
"FM"
"[x' z :[L', U M2 U']]"
"FN"
"[E :[R U' R', E2]]"
"FO"
"[y' :[U' M U, R]]"
"FP"
"[x M2 U :[M', U2]]"
"FQ"
"[U' L' U, M']"
"FR"
"[F', L S' L']"
"FS"
"x U M' U M U M' U M x'"
"FT"
"[F2 :[F', R S' R']]"
"FU"
"[x L2 U :[S', L2]]"
"FV"
"[y' :[U M2 U', R]]"
"FW"
"[x' :[U' L2 U, M2]]"
"FX"
"[y :[U' M2 U, L]]"
"GH"
"[U S' U', L']"
"GJ"
"[D :[U' R U, M']]"
"GK"
"[x :[M', U' L' U]]"
"GL"
"[L u L' :[E, L2]]"
"GM"
"[x' z :[U' L' U, M2]]"
"GN"
"[F R :[R2, S']]"
"GO"
"[R' F R :[R2, S']]"
"GP"
"[y :[L', U M U']]"
"GQ"
"[L' :[U' L' U, M']]"
"GR"
"[D :[U L U', M']]"
"GS"
"[x U' :[U' M' U, L']]"
"GT"
"[R :[L' F' L, S]]"
"GU"
"[y' :[R2, U M' U']]"
"GV"
"[x :[L' U' L, E']]"
"GW"
"[x :[M2, U' L' U]]"
"GX"
"S L F' L' U M' U2 M U S' L F L'"
"HJ"
"[z' U :[U M U', L']]"
"HK"
"[x :[M', U' L2 U]]"
"HL"
"[E, L' U L]"
"HM"
"[R F :[R2, E']]"
"HN"
"[x' U :[M', U2]]"
"HO"
"[F' L :[L2, S]]"
"HP"
"[E' :[E2, L' U L]]"
"HQ"
"[U' L U, M']"
"HR"
"B' U' S R' F' R S' R' F R U' M' U2 M B"
"HS"
"[x U' :[U' M' U, L2]]"
"HT"
"[E', R' U' R]"
"HU"
"[B' :[U2, M']]"
"HV"
"[y' L' U :[M, U2]]"
"HW"
"[D' L' :[L' F' L, S]]"
"HX"
"[y R' U :[U2, M]]"
"JK"
"[M', U' R U]"
"JL"
"[L' :[L' E2 L, U]]"
"JM"
"[F :[U' M2 U, R]]"
"JN"
"[R U' R', E']"
"JO"
"[L' E :[E, L U L']]"
"JP"
"E2 R2 E' R' U' R E R2 E2 R U R'"
"JQ"
"[M, U' R U]"
"JR"
"[R U' R', E2]"
"JS"
"[U' :[U' M U, R]]"
"JT"
"[U R' :[S, R2]]"
"JU"
"R' f2 R2 U' R2 f2 R2 U' R'"
"JV"
"[R', D M2 D']"
"JW"
"[U R U: [U2, M]]"
"JX"
"[U L :[E', L2]]"
"KL"
"[U L' U', M']"
"KM"
"[M, D R2 D']"
"KN"
"[x :[U R2 U', M']]"
"KO"
"[x :[U R U', M']]"
"KP"
"[M': [U R U', M']]"
"KQ"
"[U': [S, R' F' R]]"
"KR"
"[U L U', M']"
"KS"
"[z' x :[U' M' U, R2]]"
"KT"
"[U' R' U, M']"
"KU"
"x U' S R' F' R S' R' F R U' M' U2 M x'"
"KV"
"[U' R2 U, M']"
"KW"
"[D :[R F R', S']]"
"KX"
"[U L2 U', M']"
"LM"
"[F' L' U :[U2, M']]"
"LN"
"[L' :[U, L' E L]]"
"LO"
"[D' :[M', U L' U']]"
"LP"
"[L' U L, E']"
"LQ"
"[M, U L' U']"
"LR"
"[U' L :[S, L2]]"
"LS"
"[U :[U M U', L']]"
"LT"
"[E2, R' U' R]"
"LU"
"[U' L' U :[U2, M']]"
"LV"
"[U' R' :[E, R2]]"
"LW"
"[M2, U L' U']"
"LX"
"L2 U' L' U' L' U' L U L U L'"
"MN"
"[S' :[U, L' E L]]"
"MO"
"[F' R' :[R2, E]]"
"MP"
"[S' :[U, L E' L']]"
"MQ"
"[R U R' U', M']"
"MR"
"[L :[S', R U R']]"
"MS"
"[x U :[U M' U', R']]"
"MT"
"[U F R :[R2, S]]"
"MU"
"[R F :[R2, E]]"
"MV"
"[R' F R, S']"
"MW"
"[x :[M2, U R' U']]"
"MX"
"[x' z' U' :[R, U' M U]]"
"NO"
"[D' M D, R]"
"NP"
"[x' :[U' M2 U, R2]]"
"NQ"
"[U R' U', M']"
"NR"
"[E, L U L']"
"NS"
"[D' :[R, D' M D]]"
"NT"
"R2 E2 R2 E' R' U' R E R2 E2 R U R"
"NU"
"[F :[R2, E]]"
"NV"
"[y R U :[M', U2]]"
"NW"
"[x :[M2, U R2 U']]"
"NX"
"[y R U :[U2, M]]"
"OP"
"[D' M D, R']"
"OQ"
"[U R2 U', M']"
"OR"
"[D' :[U L U', M']]"
"OS"
"[U' :[R B R', S']]"
"OT"
"[S U L :[E, L2]]"
"OU"
"[R' F :[R2, E]]"
"OV"
"S' R' F R U' M' U2 M U' S R' F' R"
"OW"
"[x :[M2, U R U']]"
"OX"
"[R F R', S']"
"PQ"
"[U R U', M']"
"PR"
"[L :[L E' L', U]]"
"PS"
"[D' :[R', D' M D]]"
"PT"
"[E, R' U' R]"
"PU"
"[R2 F :[R2, E]]"
"PV"
"[y' :[U M2 U', R']]"
"PW"
"[x' :[U R2 U', M2]]"
"PX"
"[F, R' S' R]"
"QR"
"[U L U', M]"
"QS"
"[y :[U' M' U, R2]]"
"QT"
"[U' R' U, M]"
"QU"
"[y :[L2, U M' U']]"
"QV"
"[U' R2 U, M]"
"QW"
"[D' :[U' R2 U, M]]"
"QX"
"[U L2 U', M]"
"RS"
"[U :[U M U', L]]"
"RT"
"[R U' R' :[R2, E']]"
"RU"
"[U' L U :[U2, M']]"
"RV"
"[U' R :[E', R2]]"
"RW"
"[M2, U L U']"
"RX"
"U' L' U' L' U L U L U L'"
"ST"
"[U' :[U' M U, R']]"
"SU"
"[D' :[R F R', S']]"
"SV"
"[U' :[R2, U' M U]]"
"SW"
"B2 U' S R' F' R S' R' F R U' M' U2 M B2"
"SX"
"[U :[L2, U M U']]"
"TU"
"[U R' U' :[U2, M']]"
"TV"
"[x' :[U M' U', R']]"
"TW"
"[M2, U' R' U]"
"TX"
"[U L :[L2, E]]"
"UV"
"R2 U R2 f2 R2 U R2 f2"
"UW"
"[D2, M]"
"UX"
"L2 U' L2 f2 L2 U' L2 f2"
"VW"
"[M2, U' R2 U]"
"VX"
"[D :[M, D2]]"
"WX"
"[U L2 U', M2]"

// Corners:
"AB"
"[R' :[F, R' B2 R]]"
"AD"
"[y L :[F', L B2 L']]"
"AE"
"[U2, R' D R D' R' D R]"
"AF"
"[F :[U2, R' D' R]]"
"AG"
"[R' D R, U2]"
"AH"
"[U2, L' D' L]"
"AI"
"[l' :[U2, R' D2 R]]"
"AK"
"[U2, L' D2 L]"
"AL"
"[U :[U2, R D2 R']]"
"AN"
"[R D R' :[R' D2 R, U2]]"
"AO"
"[U2, L' D L]"
"AP"
"[R' D' R, U2]"
"AQ"
"[R' D' :[U2, R' D R]]"
"AR"
"[R' D R D' R' D R, U2]"
"AS"
"[R' D2 R, U2]"
"AT"
"[D' :[R' D' R, U2]]"
"AU"
"[R F' R' U' :[R D R', U2]]"
"AV"
"[R2 :[U, R2 D R2 D' R2]]"
"AW"
"[R D' R' :[R' D R, U2]]"
"AX"
"[z D' R' :[R' D R, U2]]"
"BD"
"[l D :[R' D' R, U]]"
"BE"
"[R :[U, R D R']]"
"BF"
"[R' :[R' D' R, U']]"
"BG"
"[R' D R, U]"
"BH"
"[U', R D' R']"
"BI"
"[R :[U2, R D R']]"
"BK"
"[D' :[R' D R, U]]"
"BL"
"[U', R D2 R']"
"BN"
"[R' D R D' R' D R, U]"
"BO"
"[U', R D R']"
"BP"
"[R' D' R, U]"
"BR"
"[R' :[R' D' R, U2]]"
"BS"
"[R' D2 R, U]"
"BT"
"[D :[U', R D' R']]"
"BU"
"[F2, R B R']"
"BV"
"[R2 D' R2 D R2, U]"
"BW"
"[U', R2 D R2 D' R2]"
"BX"
"[R' F' R, B2]"
"DE"
"[U' R :[R D R', U2]]"
"DF"
"[R' D R D' R' D R, U']"
"DG"
"[R' D R, U']"
"DH"
"[U' :[R D' R', U']]"
"DI"
"[U', R' D R D' R' D R]"
"DK"
"[D' :[R' D R, U']]"
"DL"
"[D :[R' D' R, U']]"
"DN"
"[U' R' :[U2, R' D' R]]"
"DO"
"[U' :[R D R', U']]"
"DP"
"[R' D' R, U']"
"DQ"
"[U' R :[R D R', U]]"
"DR"
"[U' R' :[U', R' D' R]]"
"DS"
"[R' D2 R, U']"
"DT"
"[U, L D2 L']"
"DU"
"[U' :[R B R', F2]]"
"DV"
"[U :[F2, U' L U L']]"
"DW"
"[R D' R' :[R' D R, U']]"
"DX"
"[R' D' R :[R U' R', D]]"
"EF"
"[L, U' R' U]"
"EG"
"[U R' :[U', R' D R]]"
"EH"
"[z U :[R' D' R, U]]"
"EI"
"[l' U' :[U2, R D' R']]"
"EK"
"[R U R' :[R' D' R, U']]"
"EL"
"[R U :[R' D R, U]]"
"EN"
"[R :[R2 D R2 D' R2, U]]"
"EO"
"[U' R :[R U' R', D']]"
"EP"
"[x :[R' D2 R, U]]"
"EQ"
"R' F' r U R U' r' F"
"ER"
"[U2, R' D R D' R' D R]"
"ES"
"[U R' :[U', R' D2 R]]"
"ET"
"[R U :[R' D' R, U]]"
"EU"
"[R :[R D2 R', U]]"
"EV"
"[D2 R :[R D' R', U]]"
"EW"
"[D R :[R D' R', U]]"
"EX"
"[R :[R D' R', U]]"
"FG"
"[U' R' U, L']"
"FH"
"[z :[R' D' R, U2]]"
"FI"
"[R' D R D' R' D R, U']"
"FK"
"[R, U L U']"
"FL"
"[D R' U' :[D', R U R']]"
"FN"
"[F' U :[R' D R, U2]]"
"FO"
"[D' R :[F, R' U R U']]"
"FP"
"[R' U' :[D', R U R']]"
"FQ"
"[R', U L U']"
"FR"
"[R B' R', F]"
"FS"
"[R B2 R', F]"
"FT"
"[F :[D', R U R']]"
"FU"
"[U' R' U :[R U' R', D]]"
"FV"
"[R' F2 :[R U' R', D']]"
"FW"
"[z :[D2, R U R']]"
"FX"
"[R2 D' :[D', R U' R']]"
"GH"
"[z' :[R U' R', D']]"
"GI"
"[D R' :[F2, R D' R' D]]"
"GK"
"[U :[D, R U' R']]"
"GL"
"R' D R U R' U' R U R' D' R U' R' U R U'"
"GN"
"[U R U :[R' D R, U2]]"
"GO"
"[U' :[D2, R' U' R]]"
"GP"
"[l :[D2, R U R']]"
"GQ"
"[R' U :[R U' R', D]]"
"GR"
"[R' D :[R' U R, D]]"
"GS"
"[U :[L' U' L, D]]"
"GT"
"[R' D :[R' U' R, D]]"
"GU"
"U R' U' R U R' D R U' R' U R U' R' D' R"
"GV"
"[z R' D :[R U' R', D2]]"
"GW"
"[F' :[R U' R', D']]"
"GX"
"[F' :[R U' R', D2]]"
"HI"
"[l' :[U2, R' D R]]"
"HK"
"[U R U' :[R D' R', U']]"
"HL"
"[D, L' U L]"
"HN"
"[U R :[R D' R', U2]]"
"HO"
"[R D' :[R' U' R, D2]]"
"HP"
"[D2, R U R']"
"HQ"
"[U' L U, R]"
"HR"
"[U2 R :[R D' R', U]]"
"HS"
"R U' R' U R D' R' U' R U R' U' R D R' U"
"HT"
"[D' :[D', R U R']]"
"HU"
"[D L' U: [F2, U' L U L']]"
"HV"
"[D2 R: [R D' R', U']]"
"HW"
"[R D' R' :[R' D R, U]]"
"HX"
"U' R D' R' U R U' R' U R D R' U' R U R'"
"IK"
"[R' :[R D' R' D, F2]]"
"IL"
"[R U :[R' D R, U2]]"
"IN"
"[R' :[U', R2 D' R2 D R2]]"
"IO"
"[l' U' :[R D R', U2]]"
"IP"
"[l' :[R' D' R, U2]]"
"IQ"
"[R D :[R D' R', U2]]"
"IR"
"R f' r2 F D' F' D r2 U' f"
"IS" //good for testing move cancellations
"[D R' D :[F2, D' R D R']]"
"IT"
"[R U :[R' D' R, U2]]"
"IU"
"[L :[F2, L' D L D']]"
"IV"
"[D' L :[L' D L D', F2]]"
"IW"
"[D R :[R D' R', U2]]"
"IX"
"[R :[R D' R', U2]]"
"KL"
"[U L' U', R]"
"KN"
"[U' R' U :[R D R', U2]]"
"KO"
"[U :[R U' R', D']]"
"KP"
"R' D' R U R' U' R U R' D R U' R' U R U'"
"KQ"
"[D' R' U :[R U' R', D]]"
"KR"
"[R :[U' L' U, R]]"
"KS"
"[U :[R U' R', D2]]"
"KT"
"[D R D :[R' U' R, D2]]"
"KU"
"[R :[R' U R U', F2]]"
"KV"
"U R' U' R U R' D' R U' R' U R U' R' D R"
"KW"
"[U R D' :[U', R' D R]]"
"KX"
"[z :[R U2 R', D]]"
"LN"
"[F' U :[R' D' R, U2]]"
"LO"
"[R D :[D, R' U' R]]"
"LP"
"[D, R U R']"
"LQ"
"[R', U L' U']"
"LR"
"r' D R D' r2 U R' U' r'"
"LS"
"[D' R D :[D2, R' U' R]]"
"LT"
"[D :[R U R', D2]]"
"LU"
"R' D R U R' U' R U R' D' R U' R' U R U'"
"LV"
"[R U' R' :[R' D R, U2]]"
"LW"
"[D R :[R D' R', U']]"
"LX"
"[z' U' :[R U R', D']]"
"NO"
"[U R U' :[R' D' R, U2]]"
"NP"
"[F', R U R2 U' R']"
"NQ"
"[R' D R D' R' D R, U]"
"NR"
"[U R :[U2, R D R']]"
"NS"
"[U' R' U :[U2, R D' R']]"
"NT"
"[U D R :[U2, R D' R']]"
"NU"
"[U' R' :[R' D R, U2]]"
"NV"
"[U' D' R' :[R' D R, U2]]"
"NW"
"[F' :[U2, R D R']]"
"NX"
"[U' D R' :[R' D R, U2]]"
"OP"
"[R D' :[R' D R, U]]"
"OQ"
"[U' R U :[R' U' R, D]]"
"OR"
"[R' U :[R' D' R, U]]"
"OS"
"[U' :[R' U' R, D']]"
"OT"
"U R U' R' D' R U R' U' R U R' D R U' R'"
"OU"
"[U' R' :[R' D R, U]]"
"OV"
"[U D R :[D2, R U' R']]"
"OW"
"R U R' D' R U' R' U R U' R' D R U R' U'"
"OX"
"[R2 D2 :[R U R', D]]"
"PQ"
"[R' U :[R U' R', D']]"
"PR"
"[R B' R', F']"
"PS"
"[l :[U2, R' D' R]]"
"PT"
"[R U R', D']"
"PU"
"[R :[R D2 R', U']]"
"PV"
"R' D' R U R' U' R U R' D R U' R' U R U'"
"PW"
"[D' R U' R' :[R' D R, U2]]"
"PX"
"[R :[R D' R', U']]"
"QR"
"[R, U' L' U]"
"QS"
"[R' U :[D2, R U' R']]"
"QT"
"[R U :[D', R U R']]"
"QU"
"[R U D :[D2, R U R']]"
"QV"
"[U R' U' :[R U R', D']]"
"QW"
"[D R U' :[R' U R, D']]"
"QX"
"[R U' :[R' U R, D']]"
"RS"
"[R' D' :[R' U R, D2]]"
"RT"
"[D' R' :[R' U R, D]]"
"RU"
"[U' R' :[R' D R, U']]"
"RV"
"[U D R :[D', R U' R']]"
"RW"
"[U R :[D', R U' R']]"
"RX"
"[R :[U R U', L]]"
"ST"
"[U' :[R', U' L U]]"
"SU"
"[x' :[D2, R U2 R']]"
"SV"
"[U D R :[D, R U' R']]"
"SW"
"[U R :[D2, R U' R']]"
"SX"
"R U' R' U R D' R' U' R U R' U' R D R' U"
"TU"
"[D' R :[R D' R', U']]"
"TV"
"[D' R D :[U, R' D' R]]"
"TW"
"U R U' R' D' R U R' U' R U R' D R U' R'"
"TX"
"[R U' D :[R' U R, D2]]"
"UV"
"[U' :[R2, U' L2 U]]"
"UW"
"[R2, U' R2 D R2 U]"
"UX"
"[F2, r D r']"
"VW"
"[R2 U R2 U' R2, D']"
"VX"
"[R2 :[D', R2 U' R2 U R2]]"
"WX"
"[z :[R U2 R', D2]]"

//parity algs:
"A"
"U2 F R U' R' U' R U R' F' R U R' U' R' F R F' U2"
"B"
"R U R' F' R U R' U' R' F R2 U' R' U'"
"D" 
"U L' U' L F L' U' L U L F' L2 U L"
"E"
"U R' U' R U R' F' R U R' U' R' F R2 U2"
"F"
"U2 R' U R U2 R' L' U R U' L"
"G"
"D U R U' R U R' F' R U R' U' R' F R2 U' R2 U' D'"
"H"
"R D' U R' F' R U R' U' R' F R2 U' R' U' R D R'"
"I"
"U2 R' F R U' R' U' R U R' F' R U R' U' R' F R F' R U2"
"K"
"U R U' R U R' F' R U R' U' R' F R2 U' R2 U'"
"L"
"D U2 R' F R2 U' R' U' R U R' F' R U R' U D'"
"N"
"U R' U R U' x' U L' U L U2 R U' R' U x"
"O"
"R D U R' F' R U R' U' R' F R2 U' R' U' R D' R'"
"P"
"U2 R' F R2 U' R' U' R U R' F' R U R' U"
"Q"
"U R U' R' U2 L R U' R' U L' U"
"R"
"U' L' U2 R U' R' U2 L R U' R' U2"
"S"
"U' L U R U R' F' R U R' U' R' F R2 U' R' U2 L' U"
"T"
"D' U2 R' F R2 U' R' U' R U R' F' R U R' U D"
"U"
"U' x U2 R2 F R F' R U2 r' U L U"
"V"
"D U R2 U' R U R' F' R U R' U' R' F R2 U' R U' D'"
"W"
"U R2 U' R U R' F' R U R' U' R' F R2 U' R U'"
"X"
"D' U R2 U' R U R' F' R U R' U' R' F R2 U' R U' D"
